-- Generated by scripts/generate-seed.mjs. Do not hand-edit; edit

-- compliance-rules.md (rules) or this script (clients) and regenerate.



-- 27 compliance rules

insert into compliance_rules (id, category, title, plain_english_rule, authority, applies_to_specialties, severity_default, example_violation, example_fix)
values ('CLAIM-001', 'Treatment and outcome claims', 'Disease cure claims', 'Marketing must not state or imply that a service or product cures, treats, or eliminates a disease or medical condition unless that claim is supported by competent and reliable scientific evidence.', 'FTC Act §5; FDA disease-claim restrictions', NULL, 'high', '"Our laser therapy cures chronic migraines."', '"Our laser therapy is used to help manage chronic migraine symptoms. Results vary by patient."')
on conflict (id) do update set
  category = excluded.category,
  title = excluded.title,
  plain_english_rule = excluded.plain_english_rule,
  authority = excluded.authority,
  applies_to_specialties = excluded.applies_to_specialties,
  severity_default = excluded.severity_default,
  example_violation = excluded.example_violation,
  example_fix = excluded.example_fix;

insert into compliance_rules (id, category, title, plain_english_rule, authority, applies_to_specialties, severity_default, example_violation, example_fix)
values ('CLAIM-002', 'Treatment and outcome claims', 'Implied permanence', 'Do not describe results as permanent, lifelong, or lasting forever unless clinical evidence supports that duration.', 'FTC Act §5', NULL, 'high', '"Permanent hair removal in six sessions."', '"Long-lasting hair reduction. Most patients see results after a series of sessions; maintenance may be needed."')
on conflict (id) do update set
  category = excluded.category,
  title = excluded.title,
  plain_english_rule = excluded.plain_english_rule,
  authority = excluded.authority,
  applies_to_specialties = excluded.applies_to_specialties,
  severity_default = excluded.severity_default,
  example_violation = excluded.example_violation,
  example_fix = excluded.example_fix;

insert into compliance_rules (id, category, title, plain_english_rule, authority, applies_to_specialties, severity_default, example_violation, example_fix)
values ('CLAIM-003', 'Treatment and outcome claims', 'Prevention claims', 'Claims that a service prevents disease require the same evidentiary support as treatment claims and are held to a high standard.', 'FTC Act §5; FDA', NULL, 'high', '"Regular cleanings prevent heart disease."', '"Research suggests a link between oral health and cardiovascular health. Regular cleanings support good oral hygiene."')
on conflict (id) do update set
  category = excluded.category,
  title = excluded.title,
  plain_english_rule = excluded.plain_english_rule,
  authority = excluded.authority,
  applies_to_specialties = excluded.applies_to_specialties,
  severity_default = excluded.severity_default,
  example_violation = excluded.example_violation,
  example_fix = excluded.example_fix;

insert into compliance_rules (id, category, title, plain_english_rule, authority, applies_to_specialties, severity_default, example_violation, example_fix)
values ('CLAIM-004', 'Treatment and outcome claims', 'Speed-of-result claims', 'Specific timeframes for results must reflect typical outcomes, not best-case ones, and must be substantiated.', 'FTC Act §5', NULL, 'medium', '"Straighter teeth in just 3 weeks."', '"Treatment length varies by case; many patients complete treatment in 6–12 months."')
on conflict (id) do update set
  category = excluded.category,
  title = excluded.title,
  plain_english_rule = excluded.plain_english_rule,
  authority = excluded.authority,
  applies_to_specialties = excluded.applies_to_specialties,
  severity_default = excluded.severity_default,
  example_violation = excluded.example_violation,
  example_fix = excluded.example_fix;

insert into compliance_rules (id, category, title, plain_english_rule, authority, applies_to_specialties, severity_default, example_violation, example_fix)
values ('CLAIM-005', 'Treatment and outcome claims', 'Comparative efficacy', 'Claims that a service is more effective than an alternative require head-to-head evidence, not general reasoning.', 'FTC Act §5', NULL, 'medium', '"More effective than traditional braces."', '"An alternative to traditional braces that some patients prefer for comfort and appearance."')
on conflict (id) do update set
  category = excluded.category,
  title = excluded.title,
  plain_english_rule = excluded.plain_english_rule,
  authority = excluded.authority,
  applies_to_specialties = excluded.applies_to_specialties,
  severity_default = excluded.severity_default,
  example_violation = excluded.example_violation,
  example_fix = excluded.example_fix;

insert into compliance_rules (id, category, title, plain_english_rule, authority, applies_to_specialties, severity_default, example_violation, example_fix)
values ('SUBS-001', 'Substantiation', 'Unsourced statistics', 'Any specific statistic must have an identifiable source. Unattributed numbers are treated as unsubstantiated.', 'FTC Act §5; FTC health products guidance', NULL, 'high', '"97% of our patients report total pain relief."', 'Either cite the source and methodology, or remove the figure and describe outcomes qualitatively.')
on conflict (id) do update set
  category = excluded.category,
  title = excluded.title,
  plain_english_rule = excluded.plain_english_rule,
  authority = excluded.authority,
  applies_to_specialties = excluded.applies_to_specialties,
  severity_default = excluded.severity_default,
  example_violation = excluded.example_violation,
  example_fix = excluded.example_fix;

insert into compliance_rules (id, category, title, plain_english_rule, authority, applies_to_specialties, severity_default, example_violation, example_fix)
values ('SUBS-002', 'Substantiation', '"Clinically proven"', 'The phrase "clinically proven" (and equivalents) requires reference to actual clinical studies supporting the specific claim being made.', 'FTC Act §5', NULL, 'high', '"Our clinically proven whitening system."', '"Our whitening system uses [ingredient], which has been studied for enamel safety." — with a citation, or drop the phrase.')
on conflict (id) do update set
  category = excluded.category,
  title = excluded.title,
  plain_english_rule = excluded.plain_english_rule,
  authority = excluded.authority,
  applies_to_specialties = excluded.applies_to_specialties,
  severity_default = excluded.severity_default,
  example_violation = excluded.example_violation,
  example_fix = excluded.example_fix;

insert into compliance_rules (id, category, title, plain_english_rule, authority, applies_to_specialties, severity_default, example_violation, example_fix)
values ('SUBS-003', 'Substantiation', '"Doctor recommended"', 'Claims of professional endorsement require a real, disclosable basis — not the practice''s own clinicians presented as independent authority.', 'FTC Act §5; FTC Endorsement Guides', NULL, 'medium', '"Doctor recommended for sensitive skin."', '"Recommended by our dermatologists for patients with sensitive skin."')
on conflict (id) do update set
  category = excluded.category,
  title = excluded.title,
  plain_english_rule = excluded.plain_english_rule,
  authority = excluded.authority,
  applies_to_specialties = excluded.applies_to_specialties,
  severity_default = excluded.severity_default,
  example_violation = excluded.example_violation,
  example_fix = excluded.example_fix;

insert into compliance_rules (id, category, title, plain_english_rule, authority, applies_to_specialties, severity_default, example_violation, example_fix)
values ('SUBS-004', 'Substantiation', 'Vague scientific framing', 'Terms like "scientifically formulated," "advanced technology," or "medical grade" imply evidentiary backing and should be avoidable or supported.', 'FTC Act §5', NULL, 'low', '"Medical grade advanced skin renewal science."', 'Describe the actual treatment and what it does, without borrowed scientific authority.')
on conflict (id) do update set
  category = excluded.category,
  title = excluded.title,
  plain_english_rule = excluded.plain_english_rule,
  authority = excluded.authority,
  applies_to_specialties = excluded.applies_to_specialties,
  severity_default = excluded.severity_default,
  example_violation = excluded.example_violation,
  example_fix = excluded.example_fix;

insert into compliance_rules (id, category, title, plain_english_rule, authority, applies_to_specialties, severity_default, example_violation, example_fix)
values ('TEST-001', 'Testimonials and endorsements', 'Atypical results without disclosure', 'A testimonial describing results better than typical must disclose what typical results actually are — a generic disclaimer is not sufficient.', 'FTC Endorsement Guides (16 CFR Part 255)', NULL, 'high', '"I lost 40 pounds in one month with their program!"', 'Include the testimonial alongside a clear statement of typical outcomes, e.g. "Most patients lose 1–2 pounds per week."')
on conflict (id) do update set
  category = excluded.category,
  title = excluded.title,
  plain_english_rule = excluded.plain_english_rule,
  authority = excluded.authority,
  applies_to_specialties = excluded.applies_to_specialties,
  severity_default = excluded.severity_default,
  example_violation = excluded.example_violation,
  example_fix = excluded.example_fix;

insert into compliance_rules (id, category, title, plain_english_rule, authority, applies_to_specialties, severity_default, example_violation, example_fix)
values ('TEST-002', 'Testimonials and endorsements', 'Undisclosed material connections', 'If a person giving a testimonial was paid, given free or discounted services, or has any other material connection to the practice, that must be disclosed clearly and near the endorsement.', 'FTC Endorsement Guides (16 CFR Part 255)', NULL, 'high', 'An influencer post praising the clinic with no disclosure.', 'Add a clear, conspicuous disclosure such as "Paid partnership" or "I received complimentary treatment."')
on conflict (id) do update set
  category = excluded.category,
  title = excluded.title,
  plain_english_rule = excluded.plain_english_rule,
  authority = excluded.authority,
  applies_to_specialties = excluded.applies_to_specialties,
  severity_default = excluded.severity_default,
  example_violation = excluded.example_violation,
  example_fix = excluded.example_fix;

insert into compliance_rules (id, category, title, plain_english_rule, authority, applies_to_specialties, severity_default, example_violation, example_fix)
values ('TEST-003', 'Testimonials and endorsements', 'Fabricated or composite testimonials', 'Testimonials must come from real patients describing their real experience. Composites, actors, or invented quotes are prohibited.', 'FTC Endorsement Guides', NULL, 'high', 'A stock-photo "patient" with a written-in-house quote.', 'Use real patient testimonials with authorization, or drop the format.')
on conflict (id) do update set
  category = excluded.category,
  title = excluded.title,
  plain_english_rule = excluded.plain_english_rule,
  authority = excluded.authority,
  applies_to_specialties = excluded.applies_to_specialties,
  severity_default = excluded.severity_default,
  example_violation = excluded.example_violation,
  example_fix = excluded.example_fix;

insert into compliance_rules (id, category, title, plain_english_rule, authority, applies_to_specialties, severity_default, example_violation, example_fix)
values ('TEST-004', 'Testimonials and endorsements', 'Testimonials making treatment claims', 'A practice cannot use a testimonial to make a claim it could not make directly. Patient words do not lower the substantiation bar.', 'FTC Act §5; FTC Endorsement Guides', NULL, 'high', '"Dr. Lee''s treatment cured my arthritis!"', 'Use testimonials that speak to experience and service rather than clinical outcomes.')
on conflict (id) do update set
  category = excluded.category,
  title = excluded.title,
  plain_english_rule = excluded.plain_english_rule,
  authority = excluded.authority,
  applies_to_specialties = excluded.applies_to_specialties,
  severity_default = excluded.severity_default,
  example_violation = excluded.example_violation,
  example_fix = excluded.example_fix;

insert into compliance_rules (id, category, title, plain_english_rule, authority, applies_to_specialties, severity_default, example_violation, example_fix)
values ('CRED-001', 'Superlatives and credentials', 'Unverifiable superlatives', 'Claims like "best," "#1," "top-rated," or "leading" require an objective, disclosable basis.', 'FTC Act §5; state medical/dental board advertising rules', NULL, 'medium', '"The best dentist in Dallas."', '"Rated 4.9 stars across 380 Google reviews." — if accurate — or describe what makes the practice distinctive.')
on conflict (id) do update set
  category = excluded.category,
  title = excluded.title,
  plain_english_rule = excluded.plain_english_rule,
  authority = excluded.authority,
  applies_to_specialties = excluded.applies_to_specialties,
  severity_default = excluded.severity_default,
  example_violation = excluded.example_violation,
  example_fix = excluded.example_fix;

insert into compliance_rules (id, category, title, plain_english_rule, authority, applies_to_specialties, severity_default, example_violation, example_fix)
values ('CRED-002', 'Superlatives and credentials', '"Specialist" without board certification', 'Many state boards restrict "specialist" and "specializing in" to clinicians holding recognised board certification in that specialty.', 'State medical/dental board advertising rules', NULL, 'high', '"Our specialists in cosmetic dentistry."', '"Our dentists have advanced training in cosmetic procedures."')
on conflict (id) do update set
  category = excluded.category,
  title = excluded.title,
  plain_english_rule = excluded.plain_english_rule,
  authority = excluded.authority,
  applies_to_specialties = excluded.applies_to_specialties,
  severity_default = excluded.severity_default,
  example_violation = excluded.example_violation,
  example_fix = excluded.example_fix;

insert into compliance_rules (id, category, title, plain_english_rule, authority, applies_to_specialties, severity_default, example_violation, example_fix)
values ('CRED-003', 'Superlatives and credentials', 'Misleading credential presentation', 'Credentials, affiliations, and memberships must be current, accurately named, and not presented in a way that implies more than they are.', 'State board advertising rules; FTC Act §5', NULL, 'medium', '"Member of the American Academy of Cosmetic Dentistry" where membership is lapsed or is a paid directory listing presented as an honour.', 'State the affiliation accurately and currently.')
on conflict (id) do update set
  category = excluded.category,
  title = excluded.title,
  plain_english_rule = excluded.plain_english_rule,
  authority = excluded.authority,
  applies_to_specialties = excluded.applies_to_specialties,
  severity_default = excluded.severity_default,
  example_violation = excluded.example_violation,
  example_fix = excluded.example_fix;

insert into compliance_rules (id, category, title, plain_english_rule, authority, applies_to_specialties, severity_default, example_violation, example_fix)
values ('CRED-004', 'Superlatives and credentials', 'Award and ranking claims', 'Awards must name the awarding body and year, and must not be pay-to- list awards presented as merit-based.', 'FTC Act §5; state board rules', NULL, 'medium', '"Award-winning practice."', '"Named Best of [City] by [Publication], 2025."')
on conflict (id) do update set
  category = excluded.category,
  title = excluded.title,
  plain_english_rule = excluded.plain_english_rule,
  authority = excluded.authority,
  applies_to_specialties = excluded.applies_to_specialties,
  severity_default = excluded.severity_default,
  example_violation = excluded.example_violation,
  example_fix = excluded.example_fix;

insert into compliance_rules (id, category, title, plain_english_rule, authority, applies_to_specialties, severity_default, example_violation, example_fix)
values ('GUAR-001', 'Guarantees and risk language', 'Outcome guarantees', 'Do not guarantee a clinical result. Individual outcomes vary and guarantees are treated as deceptive.', 'FTC Act §5; state board advertising rules', NULL, 'high', '"Guaranteed results or your money back."', 'Describe the satisfaction or refund policy without guaranteeing a clinical outcome.')
on conflict (id) do update set
  category = excluded.category,
  title = excluded.title,
  plain_english_rule = excluded.plain_english_rule,
  authority = excluded.authority,
  applies_to_specialties = excluded.applies_to_specialties,
  severity_default = excluded.severity_default,
  example_violation = excluded.example_violation,
  example_fix = excluded.example_fix;

insert into compliance_rules (id, category, title, plain_english_rule, authority, applies_to_specialties, severity_default, example_violation, example_fix)
values ('GUAR-002', 'Guarantees and risk language', '"Painless" and absolute comfort claims', 'Absolute claims about the absence of pain or discomfort are not supportable across patients.', 'FTC Act §5', NULL, 'medium', '"Completely painless procedure."', '"We use local anaesthetic and sedation options to keep you comfortable."')
on conflict (id) do update set
  category = excluded.category,
  title = excluded.title,
  plain_english_rule = excluded.plain_english_rule,
  authority = excluded.authority,
  applies_to_specialties = excluded.applies_to_specialties,
  severity_default = excluded.severity_default,
  example_violation = excluded.example_violation,
  example_fix = excluded.example_fix;

insert into compliance_rules (id, category, title, plain_english_rule, authority, applies_to_specialties, severity_default, example_violation, example_fix)
values ('GUAR-003', 'Guarantees and risk language', '"No risk" / "completely safe"', 'No medical or cosmetic procedure is risk-free. Claims of zero risk or complete safety are prohibited and may also omit material risk information.', 'FTC Act §5; FDA', NULL, 'high', '"A completely safe procedure with no risks."', '"A well-established procedure. Your provider will discuss risks and whether it''s right for you."')
on conflict (id) do update set
  category = excluded.category,
  title = excluded.title,
  plain_english_rule = excluded.plain_english_rule,
  authority = excluded.authority,
  applies_to_specialties = excluded.applies_to_specialties,
  severity_default = excluded.severity_default,
  example_violation = excluded.example_violation,
  example_fix = excluded.example_fix;

insert into compliance_rules (id, category, title, plain_english_rule, authority, applies_to_specialties, severity_default, example_violation, example_fix)
values ('GUAR-004', 'Guarantees and risk language', 'Omission of material risk', 'Where a procedure carries significant known risks or requires recovery, marketing must not present it in a way that omits that material information.', 'FTC Act §5', NULL, 'medium', '"Walk in on your lunch break, walk out with a new look."', 'Mention that a consultation is required and that recovery time varies.')
on conflict (id) do update set
  category = excluded.category,
  title = excluded.title,
  plain_english_rule = excluded.plain_english_rule,
  authority = excluded.authority,
  applies_to_specialties = excluded.applies_to_specialties,
  severity_default = excluded.severity_default,
  example_violation = excluded.example_violation,
  example_fix = excluded.example_fix;

insert into compliance_rules (id, category, title, plain_english_rule, authority, applies_to_specialties, severity_default, example_violation, example_fix)
values ('PRIV-001', 'Patient privacy', 'Patient photos without authorization', 'Using a patient''s image — including before/after photos — for marketing requires prior written HIPAA authorization. Consent to treatment is not consent to marketing use.', 'HIPAA Privacy Rule (45 CFR 164.508)', NULL, 'high', 'Posting a before/after photo from a patient chart.', 'Obtain and retain signed marketing authorization before any use.')
on conflict (id) do update set
  category = excluded.category,
  title = excluded.title,
  plain_english_rule = excluded.plain_english_rule,
  authority = excluded.authority,
  applies_to_specialties = excluded.applies_to_specialties,
  severity_default = excluded.severity_default,
  example_violation = excluded.example_violation,
  example_fix = excluded.example_fix;

insert into compliance_rules (id, category, title, plain_english_rule, authority, applies_to_specialties, severity_default, example_violation, example_fix)
values ('PRIV-002', 'Patient privacy', 'Identifiable patient details', 'Names, ages, dates of service, conditions, or any combination that could identify a patient must not appear in marketing without authorization.', 'HIPAA Privacy Rule', NULL, 'high', '"Sarah, 34, came to us in March with severe TMJ..."', 'Remove identifiers, or obtain written authorization.')
on conflict (id) do update set
  category = excluded.category,
  title = excluded.title,
  plain_english_rule = excluded.plain_english_rule,
  authority = excluded.authority,
  applies_to_specialties = excluded.applies_to_specialties,
  severity_default = excluded.severity_default,
  example_violation = excluded.example_violation,
  example_fix = excluded.example_fix;

insert into compliance_rules (id, category, title, plain_english_rule, authority, applies_to_specialties, severity_default, example_violation, example_fix)
values ('PRIV-003', 'Patient privacy', 'Responding to online reviews', 'Responding publicly to a patient review must not confirm that the person is a patient or disclose any treatment detail, even to correct an inaccurate review.', 'HIPAA Privacy Rule', NULL, 'high', '"We''re sorry your root canal was uncomfortable, Mr. Hassan."', '"Thank you for the feedback. Please contact our office manager so we can discuss your experience directly."')
on conflict (id) do update set
  category = excluded.category,
  title = excluded.title,
  plain_english_rule = excluded.plain_english_rule,
  authority = excluded.authority,
  applies_to_specialties = excluded.applies_to_specialties,
  severity_default = excluded.severity_default,
  example_violation = excluded.example_violation,
  example_fix = excluded.example_fix;

insert into compliance_rules (id, category, title, plain_english_rule, authority, applies_to_specialties, severity_default, example_violation, example_fix)
values ('DISC-001', 'Required disclosures', 'Missing results-vary disclosure', 'Content showing or describing outcomes should carry a clear statement that individual results vary.', 'FTC Endorsement Guides; FTC Act §5', NULL, 'low', 'A results-focused post with no qualifier.', 'Add "Individual results vary" prominently, not buried in fine print.')
on conflict (id) do update set
  category = excluded.category,
  title = excluded.title,
  plain_english_rule = excluded.plain_english_rule,
  authority = excluded.authority,
  applies_to_specialties = excluded.applies_to_specialties,
  severity_default = excluded.severity_default,
  example_violation = excluded.example_violation,
  example_fix = excluded.example_fix;

insert into compliance_rules (id, category, title, plain_english_rule, authority, applies_to_specialties, severity_default, example_violation, example_fix)
values ('DISC-002', 'Required disclosures', 'Before/after photo disclosures', 'Before/after images should disclose whether they are actual patients, whether images are retouched or filtered, and the timeframe between them.', 'FTC Act §5', NULL, 'medium', 'An unlabelled before/after grid.', '"Actual patient. Photos taken 6 months apart. Not retouched."')
on conflict (id) do update set
  category = excluded.category,
  title = excluded.title,
  plain_english_rule = excluded.plain_english_rule,
  authority = excluded.authority,
  applies_to_specialties = excluded.applies_to_specialties,
  severity_default = excluded.severity_default,
  example_violation = excluded.example_violation,
  example_fix = excluded.example_fix;

insert into compliance_rules (id, category, title, plain_english_rule, authority, applies_to_specialties, severity_default, example_violation, example_fix)
values ('DISC-003', 'Required disclosures', 'Pricing and offer terms', 'Promotional pricing must disclose material conditions — what''s included, exclusions, expiry, and whether it''s a starting price.', 'FTC Act §5', NULL, 'medium', '"Invisalign for $99/month!"', '"Invisalign from $99/month with approved credit, 36-month term. Final cost determined at consultation."')
on conflict (id) do update set
  category = excluded.category,
  title = excluded.title,
  plain_english_rule = excluded.plain_english_rule,
  authority = excluded.authority,
  applies_to_specialties = excluded.applies_to_specialties,
  severity_default = excluded.severity_default,
  example_violation = excluded.example_violation,
  example_fix = excluded.example_fix;



-- 4 demo clients (one per specialty)

insert into clients (id, name, specialty, state, brand_tone)
values ('fcf02b32-e149-4899-8d92-27669cd46ad2', 'Maple Street Dental', 'dental', 'OH', 'warm, reassuring, family-friendly')
on conflict (id) do update set
  name = excluded.name,
  specialty = excluded.specialty,
  state = excluded.state,
  brand_tone = excluded.brand_tone;

insert into clients (id, name, specialty, state, brand_tone)
values ('49e97159-0b21-479f-8875-0600b8b67908', 'Bright Sky Dermatology', 'dermatology', 'CA', 'clinical but approachable, confidence-forward')
on conflict (id) do update set
  name = excluded.name,
  specialty = excluded.specialty,
  state = excluded.state,
  brand_tone = excluded.brand_tone;

insert into clients (id, name, specialty, state, brand_tone)
values ('84133b03-6ac1-43ba-917d-d38910f1d59f', 'Willow & Glow Med Spa', 'med_spa', 'FL', 'upscale, calming, aspirational')
on conflict (id) do update set
  name = excluded.name,
  specialty = excluded.specialty,
  state = excluded.state,
  brand_tone = excluded.brand_tone;

insert into clients (id, name, specialty, state, brand_tone)
values ('4bac44f1-8987-4fb8-91fc-63fc79f83b77', 'Cascade Chiropractic & Wellness', 'chiropractic', 'WA', 'energetic, practical, no-nonsense')
on conflict (id) do update set
  name = excluded.name,
  specialty = excluded.specialty,
  state = excluded.state,
  brand_tone = excluded.brand_tone;

